{
    "Gráfico 18.1": "Traceback (most recent call last):\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/g18.1--g18.2.py\", line 75, in <module>\n    df = c.open_file(dbs_path, os.listdir(dbs_path)[0], 'csv', sep=';', encoding='cp1252', skiprows=3)\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/functions.py\", line 95, in open_file\n    dataframe = pd.read_csv(os.path.join(dir_path, file_path),\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 626, in _read\n    return parser.read(nrows)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 1923, in read\n    ) = self._engine.read(  # type: ignore[attr-defined]\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 234, in read\n    chunks = self._reader.read_low_memory(nrows)\n  File \"parsers.pyx\", line 838, in pandas._libs.parsers.TextReader.read_low_memory\n  File \"parsers.pyx\", line 905, in pandas._libs.parsers.TextReader._read_rows\n  File \"parsers.pyx\", line 874, in pandas._libs.parsers.TextReader._tokenize_rows\n  File \"parsers.pyx\", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status\n  File \"parsers.pyx\", line 2061, in pandas._libs.parsers.raise_parser_error\npandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 13, saw 4\n\n",
    "Gráfico 18.2": "Traceback (most recent call last):\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/g18.1--g18.2.py\", line 143, in <module>\n    df = c.open_file(dbs_path, os.listdir(dbs_path)[0], 'csv', sep=';', encoding='cp1252', skiprows=3)\n  File \"/home/runner/work/T25/T25/Scripts/Daniel/functions.py\", line 95, in open_file\n    dataframe = pd.read_csv(os.path.join(dir_path, file_path),\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 626, in _read\n    return parser.read(nrows)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 1923, in read\n    ) = self._engine.read(  # type: ignore[attr-defined]\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 234, in read\n    chunks = self._reader.read_low_memory(nrows)\n  File \"parsers.pyx\", line 838, in pandas._libs.parsers.TextReader.read_low_memory\n  File \"parsers.pyx\", line 905, in pandas._libs.parsers.TextReader._read_rows\n  File \"parsers.pyx\", line 874, in pandas._libs.parsers.TextReader._tokenize_rows\n  File \"parsers.pyx\", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status\n  File \"parsers.pyx\", line 2061, in pandas._libs.parsers.raise_parser_error\npandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 13, saw 4\n\n"
}