{
    "https://servicodados.ibge.gov.br/api/v1/downloads/estatisticas?caminho=Contas_Regionais/2020/xls (Conta da Produção)": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g3.1--g3.2--g3.3--g3.4--g3.5--g3.6--g3.7--g3.8--g3.9--g3.10.py\", line 47, in <module>\n    if response.status_code == 200:\nNameError: name 'response' is not defined\n",
    "Gráfico 3.1": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g3.1--g3.2--g3.3--g3.4--g3.5--g3.6--g3.7--g3.8--g3.9--g3.10.py\", line 151, in <module>\n    data = c.open_file(dbs_path, 'ibge_conta_producao.zip', 'zip', excel_name='Tabela17', sheet_name='Tabela17.3', skiprows=1)\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 124, in open_file\n    with zipfile.ZipFile(os.path.join(dir_path, file_path), 'r') as zfile:\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1251, in __init__\n    self.fp = io.open(file, filemode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmp1kohia7e\\\\ibge_conta_producao.zip'\n",
    "Gráfico 3.2": "Traceback (most recent call last):\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\g3.1--g3.2--g3.3--g3.4--g3.5--g3.6--g3.7--g3.8--g3.9--g3.10.py\", line 212, in <module>\n    data = c.open_file(dbs_path, 'ibge_conta_producao.zip', 'zip', excel_name='Tabela17', sheet_name='Tabela17.3', skiprows=1)\n  File \"D:\\a\\T25\\T25\\Scripts\\Daniel\\functions.py\", line 124, in open_file\n    with zipfile.ZipFile(os.path.join(dir_path, file_path), 'r') as zfile:\n  File \"C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\lib\\zipfile.py\", line 1251, in __init__\n    self.fp = io.open(file, filemode)\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\tmp1kohia7e\\\\ibge_conta_producao.zip'\n"
}